### ISSUE TITLE
[LG Gram] battery_care_limit inactive

### ISSUE THREAD

**Issue by alexyao2015** [linrunner/TLP#757] opened 2024-09-02 02:22 UTC
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've provided all required `tlp-stat` outputs via [Gist](https://gist.github.com/) (see below)

**Describe the bug**
I recently purchased a current gen LG gram and am attempting to use tlp, but see an inactive message when running `tlp-stat`.

**Expected behavior**
TLP to function correctly.

**To Reproduce**
Presumably, some kernel features are missing, but I'm not sure where this should be reported. Attempting to manually set the battery care limit also gives an error. Let me know what other diagnostics would be useful, if any.

```
echo 80 | sudo tee /sys/devices/platform/lg-laptop/battery_care_limit
80
tee: /sys/devices/platform/lg-laptop/battery_care_limit: Input/output error
```

Does the problem occur on battery or AC or both? Both

```
tlp-stat -b
--- TLP 1.6.1 --------------------------------------------

+++ Battery Care
Plugin: lg-legacy
Supported features: none available
Driver usage:
* vendor (lg_laptop) = inactive (laptop not supported)

+++ Battery Status: BAT0
/sys/class/power_supply/BAT0/manufacturer                   =  LG 
LGys/class/power_supply/BAT0/model_name                     = LGES
/sys/class/power_supply/BAT0/cycle_count                    =      1
/sys/class/power_supply/BAT0/energy_full_design             =  77020 [mWh]
/sys/class/power_supply/BAT0/energy_full                    =  79800 [mWh]
/sys/class/power_supply/BAT0/energy_now                     =  76800 [mWh]
/sys/class/power_supply/BAT0/power_now                      =   8355 [mW]
/sys/class/power_supply/BAT0/status                         = Discharging

Charge                                                      =   96.2 [%]
Capacity                                                    =  103.6 [%]
```

**Comment by linrunner** [comment] 2024-09-02 05:25
Duplicate of #747 

Your problem is already known. As the output shows, TLP is _not_ the cause, but kernels >  6.8 have a regression/are defective. I'll close here, you can follow the progress in the other issue and contribute there if possible.

**Closed** 2024-09-02 05:30 UTC
Labels: kernel issue, duplicate, battery care
