### ISSUE TITLE
System freezes and reboots on Ubuntu running on Lenovo X1 carbon gen 8

### ISSUE THREAD

**Issue by bpavacic** [linrunner/TLP#615] opened 2022-02-01 01:32 UTC
I am using version 1.3.1-2  installed from Ubuntu 21.10 .deb package on Lenovo X1 Carbon gen 8.
The battery is kept charged between 75% and 85%, the settings I have set on some previous version of TLP and/or some older kernel.

The problem is that when I issue TLP commands the system freezes for 10 seconds or so and then reboots.

Anyone experiencing the same problems? Please let me know if you need more information to debug this issue.

```
$ uname -a 
Linux thinkpad 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ grep -v "^#" /etc/tlp.conf |grep -v "^$"
START_CHARGE_THRESH_BAT0=75
STOP_CHARGE_THRESH_BAT0=85

$ service tlp status
○ tlp.service - TLP system startup/shutdown
     Loaded: loaded (/lib/systemd/system/tlp.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: https://linrunner.de/tlp

$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

```

**Comment by bpavacic** [comment] 2022-02-01 01:44
![PXL_20220201_013656854](https://user-images.githubusercontent.com/10812430/151901004-92545dfd-21fa-4f55-9016-59b0b56c00eb.jpg)

Attaching the output of "tlp chargeonce" run as root, seconds before the machine rebooted

**Comment by linrunner** [comment] 2022-02-02 06:43
Duplicate of #599

**Comment by linrunner** [comment] 2022-02-02 06:44
You need a newer version of acpi_call --> https://github.com/nix-community/acpi_call/issues/15

**Closed by linrunner** 2022-02-02 06:44 UTC
Labels: incomplete, not related to TLP, acpi_call

**Comment by bpavacic** [comment] 2022-02-02 13:13
Thank you.
Upgrading acpi_call from 1.1.0 to 1.2.2 fixed the problem. I have used the instructions [here](https://blog.monosoul.dev/2021/10/16/ubuntu-21-10-and-acpi-call-dkms-bug/)
